<a href="https://colab.research.google.com/github/RixzFahad/Met-Data-Science-And-Analyst/blob/main/2Darrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***2-Dimensional Array's***

In [5]:
import numpy as np


In [12]:
a = np.array([[1,2,3], [4,5,6]])
#Find the number of row's and columns
a.shape
#find the dimentionality of an array
a.ndim
#find the number of elements in a arrays
a.size
#find the data type of element in aaray
a.dtype
#find the each elemnets occupency in byte's
a.itemsize

8

In [14]:
a = np.array([[1,2,3], [4,5,6]])
#Print the entire first row
#Syntax:- [row_ind, col_ind]
print(a[0])

[1 2 3]


In [15]:
#Print 5  from above Array
print(a[1,1])

5


In [13]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
#print the second Row
print(b[1])

[5 6 7 8]


In [21]:
#Access 6-12 From Array
print(b[1:3,1:4])

[[ 6  7  8]
 [10 11 12]]


# ***Transpose:-***
*Convert rows into columns and vice versa.*

In [23]:
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# ***Dot Product Matrix Multipilication:-***
***This Is Nothing Only Cross Multipilication***

In [26]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
#Apply the dot Matrix Product on Above
print(a.dot(b))
a@b

[[13 16]
 [29 36]]


array([[13, 16],
       [29, 36]])

# ***Inverse***

In [28]:
a = np.array([[1,2],[3,4]])
b = np.linalg.inv(a)
print(b)

[[-2.   1. ]
 [ 1.5 -0.5]]


# ***Diagonal***

In [30]:
#Find the diagonal
e = np.diag(a)
print(e)

[1 4]


# ***Boolean Indexing:-***

In [31]:
xy = np.array([[1,2],[3,4],[5,6]])
# Chec the element of a is greator then 2
print(xy>2)

[[False False]
 [ True  True]
 [ True  True]]


In [32]:
#print the numbers greator than 2
print(xy[xy>2])

[3 4 5 6]


In [35]:
l = [1,2,3,4,5,6]
# check the number greator than 2
for i in l:
  if i>2:
    print(True)
  else:
    print(False)

False
False
True
True
True
True


In [36]:
a = np.array([[1,2],[3,4],[5,6]])

# print the numbers greater than 2 and numbers less than 2 print it as -1
# np.where(logic, true, false)

b = np.where(a > 2, a, -1)
print(b)


[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [37]:
# compute the indexes where the condition is even number
c = np.array([10, 21, 13, 15, 16, 19, 18, 23])

# np.argwhere(logic) gives the index where the condition is true
d = np.argwhere(c % 2 == 0).flatten()

print(d)



[0 4 6]


# ***Reshaping Of An Array***

In [38]:
#Create An Array Of Range Of 10
yx = np.arange(10)
print(yx)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
# Convert Above Arrays into  rows and two columns
b =yx.reshape(5,2)
print(b)
print(b.T)
#Syntax:- np.rehshape(row, col)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


# ***Contatination***

In [42]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
#combine and contatinate the above arrays
c = np.concatenate((a,b), axis=1)
print(c)

[[1 2 3 4]
 [3 4 5 6]]


# ***Hstack***

In [43]:
d = np.hstack((a,b))
print(d)

[[1 2 3 4]
 [3 4 5 6]]


# ***Vstack***

In [44]:
r = np.vstack((a,b))
print(r)

[[1 2]
 [3 4]
 [3 4]
 [5 6]]


# ***BroadCasting Method:-***
Broadcasting is a powerful mechanism in NumPy that allows arithmetic operations on arrays of different shapes. Two arrays are broadcastable if their dimensions are equal or if one of the dimensions is 1.

In [45]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

y = np.array([1,0,1])

z = x + y
print(z)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


# ***Copying Of An Array:***

In [46]:
import numpy as np

# Create an original NumPy array
a = np.array([1, 2, 3])

# Create a deep copy of array 'a'
# Changes made to 'b' will NOT affect 'a'
b = a.copy()

# Modify the copied array
b[1] = 5

# Print original array
# Output remains unchanged because 'b' is an independent copy
print(a)   # [1 2 3]


[1 2 3]


`Generating Arrays:-`

In [48]:
#Generates Arrays With Xeros with 2 row's and three column's.
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [52]:
#Generates Arrays With One with 2 row's and three column's.
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [55]:
#Generates Arrays With Specific Number with 2 row's and three column's.
c = np.full((2,3),9)
print(c)

[[9 9 9]
 [9 9 9]]


In [56]:
# Generate An Array With Identity Matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# ***Usual Command For Numpy :-***

In [57]:
# 1. Create an array  --> np.array()
# Used to create a NumPy array from a list or tuple

# 2. Check rows and columns (shape) of an array  --> arr.shape
# Returns (number_of_rows, number_of_columns)

# 3. Check the number of dimensions of an array  --> arr.ndim
# 1D, 2D, 3D, etc.

# 4. Check the data type of elements in the array  --> arr.dtype
# Example: int32, float64

# 5. Check the total number of elements in the array  --> arr.size
# Returns rows × columns

# 6. Apply dot product on arrays  --> np.dot(arr1, arr2)
# Used for matrix multiplication or vector dot product

# 7. Create boolean indexing on an array  --> arr > condition
# Returns True/False values

# 8. Apply condition on array  --> np.where(condition, True_value, False_value)
# Used for conditional replacement

# 9. Compute indices where condition is True  --> np.argwhere(condition)
# Returns indices of True elements (2D output)

# 10. Apply transpose of an array  --> arr.T
# Converts rows to columns

# 11. Check diagonal elements of an array  --> np.diag(arr)
# Extracts diagonal elements of a matrix

# 12. Compute inverse of a matrix  --> np.linalg.inv(arr)
# Works only for square & non-singular matrices

# 13. Reshape an array  --> np.reshape(arr, (rows, cols))
# Total elements must remain the same

# 14. Concatenate arrays  --> np.concatenate((arr1, arr2), axis=0 or 1)
# axis=0 → row-wise, axis=1 → column-wise

# 15. Copy an array  --> arr.copy()
# Creates a deep copy; changes do not affect original array
