<a href="https://colab.research.google.com/github/RixzFahad/Met-Data-Science-And-Analyst/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

Its A core libarary for scientific computing in python

*   The Central Object of Numpy is Numpy Array's.
*   Numpy array's are high performance multidimensinal objects which are designed for the mathameticals operation's



***Type Of Arrays We Having Is Array's- Numpy***

*   1D - An array with one dimension and a single axis (axis = 0)
*   2D - An array with two dimensions (rows and columns)
*   3D -3D Array: An array with three dimensions (layers, rows, columns)
axes: axis = 0 → layers, axis = 1 → rows, axis = 2 → columns.

In [ ]:
# What are the use cases and mathematical operations achieved using NumPy?

"""
1. Dot product / Inner product (used in linear and logistic regression)
2. Matrix multiplication
3. Solving linear systems of equations
4. Matrix inverse
5. Determinant calculation
6. Random number generation
7. Statistical operations
"""


In [ ]:
#What Is Pip
#Pip Is A Python Package Manager Which Is used to install new packages into python

In [4]:
#Installing Numpy
!pip install numpy

In [9]:
#Check the Version of numpyimport numpy as np
np.__version__

'2.0.2'

***The Central Object Of Numpy Are Array's***

In [14]:
#How can we create an arrays.---- Arrays Can Be Created From Existing Data.

#Convert a List Into Array
li = (1,2,3,4)
f = np.array(li)
print(f)

#Find the number of rows and columns in a arrays
f.shape

#Find the number of elements in arrays
f.size

#Find the dimentionality of arrays
f.ndim

#Find the data type of each elements in arrays
f.dtype

#Find the storage of each elements in the bytes
f.itemsize

[1 2 3 4]


8

In [5]:
import numpy as np

In [ ]:
#How can we create a arrays?
li = [1,2,3,4,5]
#Convert Above List Into Arrays
a = np.array(li)
print(a)
#Find the number of row and columns in array
a.shape
#Find the number of elements in arrays
a.size
#Find the dimentionality of arrays
a.ndim
#find the data type of each element inside arrays
a.dtype
#Find the storage of each elements in the bytes
a.itemsize

[1 2 3 4 5]


8

Array's Are Defind As--

*   Ordered
*   Immutable
*   Allow's Duplicate





# **Essential Method's In Numpy.**

In [18]:
#Access the elements from numpy.
C = np.array([1,2,3,4,5])
# Print 2 From Above Arrays
print(C[1])

#Reverse The Entire Array
print(C[::-1])

2
[5 4 3 2 1]


In [19]:
# In Arrays We Can Replace The Data But Can't Add And Remove
#Replace 2 With 69
C[1]= 69
print(C[1])

69


***Elements Wise Math Operation's***

In [21]:
x = np.array([22,33,44,55,66])
print(C+x)

[ 23 102  47  59  71]


In [24]:
Y = np.array([4,5,6,7])
#Sum all the elements From the array
print(sum(Y))

#Print the maximum arrays from the above list
print(max(Y))

#Print Minimum From the above Lsit
print(min(Y))

22
7
4


In [ ]:
# What is Vector Addition
# When We Apply An Addition On Array Of The Same Length Or Size Is Known As Vector Addition

# ***What Are The Diffrences Between Arrays And List.?***

In [ ]:
# 1. Data Type
# List  : Can store elements of different data types
# Array : Stores elements of the same data type

# 2. Performance
# List  : Slower for numerical computations
# Array : Faster and optimized for numerical operations

# 3. Memory Usage
# List  : Uses more memory
# Array : Uses less memory due to fixed data type

# 4. Mathematical Operations
# List  : Does not support element-wise operations directly
# Array : Supports element-wise operations

# 5. Multidimensional Support
# List  : Uses nested lists (less efficient)
# Array : Built-in support for multidimensional data

# 6. Functionality
# List  : General-purpose data structure
# Array : Designed for scientific and mathematical computing

# 7. Speed of Computation
# List  : Slower due to Python loops
# Array : Faster due to vectorized operations

# 8. Library Requirement
# List  : Built-in, no import required
# Array : Requires NumPy library


In [25]:
# What is the difference between arrays and lists?

import numpy as np

# List example
l = [1, 2, 3]

# Add element to list
l.append(4)
print(l)
# Output: [1, 2, 3, 4]

# NumPy array example
e = np.array([1, 2, 3])

# Arrays do NOT support append like lists
# e.append(4)  ❌ (will cause an error)

# Correct way: element-wise operation or create a new array
f = e + np.array([4, 4, 4])
print(f)
# Output: [5 6 7]

# Key difference shown:
# List -> append adds a new element
# Array -> operations are element-wise, size is fixed


[1, 2, 3, 4]
[5 6 7]


In [26]:
"""
When we add a single element (scalar) to an existing NumPy array,
the scalar value is automatically applied to each element of the array.
This concept is known as the Broadcasting method.
"""

# Using Python list
l = [1, 2, 3, 4, 5, 6]

# Print list elements multiplied by 2
for i in l:
    print(i * 2, end=" ")

# Output: 2 4 6 8 10 12


# Using NumPy array (Broadcasting)
import numpy as np

g = np.array([1, 2, 3, 4, 5, 6])
print(g * 2)

# Output: [ 2  4  6  8 10 12 ]


2 4 6 8 10 12 [ 2  4  6  8 10 12]


# ***Define Dot Product***

In [27]:
# Dot product is the multiplication of corresponding elements of two arrays
# followed by the sum of those products.

import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

# Easy method using NumPy
dot = np.dot(a, b)
print(dot)
# Output: 11

# Manual method
c = a * b          # element-wise multiplication
print(c)           # [3 8]
print(c.sum())     # 11


11
[3 8]
11


In [28]:
# Dot product using different NumPy methods

import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

# Using dot() method
e = a.dot(b)
print(e)
# Output: 11

# Using @ operator (matrix / dot multiplication)
f = a @ b
print(f)
# Output: 11


11
11
