<a href="https://colab.research.google.com/github/RixzFahad/Met-Data-Science-And-Analyst/blob/main/Pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [4]:
# loc()- Used To Locate Row's
df.columns


Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [6]:
df["total_rooms"].loc[50:100]

50      540.0
51     1109.0
52     1327.0
53     1615.0
54     1617.0
55     1879.0
56     1715.0
57     1190.0
58     2804.0
59      807.0
60     2578.0
61     1583.0
62     2231.0
63     1527.0
64     1459.0
65     1697.0
66     1513.0
67     2429.0
68     1712.0
69     2266.0
70     2565.0
71     1540.0
72      666.0
73     1004.0
74      565.0
75     2652.0
76     2164.0
77     1672.0
78     1311.0
79     1171.0
80     2372.0
81     1178.0
82     2511.0
83     1185.0
84     1568.0
85     1278.0
86     1365.0
87     1039.0
88     1207.0
89     1494.0
90     2276.0
91     1152.0
92     1534.0
93     1413.0
94     1161.0
95      805.0
96     1088.0
97     1687.0
98     2494.0
99     1608.0
100    2183.0
Name: total_rooms, dtype: float64

In [7]:
#Locate the row of 'polpulation', 'households' 'median_income' by using the loc from 50 to 100.
df[['population','households','median_income']].loc[50:100]

population  households  median_income
50        122.0        63.0         1.3333
51       1006.0       253.0         2.1630
52        784.0       231.0         1.8793
53       1307.0       345.0         1.4583
54       1416.0       401.0         1.9750
55       1376.0       337.0         1.9911
56       1166.0       333.0         2.2417
57       1113.0       258.0         2.3571
58       2807.0       594.0         2.0625
59        246.0       102.0         2.5391
60       2082.0       565.0         1.7159
61        933.0       318.0         2.4063
62       1568.0       510.0         1.5217
63       1453.0       332.0         1.7350
64       1148.0       388.0         1.5372
65        911.0       254.0         4.3523
66       1121.0       381.0         1.9464
67       1188.0       430.0         3.0091
68       1370.0       377.0         1.2750
69        952.0       360.0         5.4349
70       1447.0       473.0         3.2593
71       1013.0       274.0         2.5664
72        580.0       160.0         2.1136
73        697.0       201.0         1.6351
74        692.0       141.0         1.2083
75       1767.0       536.0         2.8025
76       1164.0       421.0         3.8177
77       1335.0       397.0         1.5987
78       1193.0       351.0         2.1979
79       1024.0       298.0         1.3882
80       2283.0       767.0         1.1707
81       1377.0       429.0         1.3373
82       1583.0       469.0         3.0603
83        615.0       191.0         4.6154
84        848.0       245.0         3.1597
85        653.0       185.0         4.4821
86        825.0       250.0         3.2396
87        728.0       246.0         1.7411
88        804.0       288.0         1.9531
89        959.0       284.0         3.5282
90       1184.0       513.0         1.8750
91        621.0       208.0         3.6042
92        871.0       222.0         6.2715
93        803.0       277.0         4.3021
94        724.0       186.0         3.1827
95        458.0       143.0         4.4750
96        533.0       201.0         3.6597
97        762.0       451.0         1.6635
98       1416.0       421.0         5.7843
99        862.0       248.0         4.8750
100      1000.0       287.0         6.3814

In [11]:
#apply the condition in dataframe in particular columns
df['total_rooms']%2==0

0         True
1         True
2         True
3        False
4         True
         ...  
16995    False
16996    False
16997    False
16998     True
16999     True
Name: total_rooms, Length: 17000, dtype: bool

In [12]:
#in dataframe To Appplying the condition's we use df.loc
df.loc[df['total_rooms']%2==0]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
4        -114.57     33.57                20.0       1454.0           326.0   
7        -114.59     34.83                41.0        812.0           168.0   
...          ...       ...                 ...          ...             ...   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
4           624.0       262.0         1.9250             65500.0  
7           375.0       158.0         1.7083             48500.0  
...           ...         ...            ...                 ...  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[8355 rows x 9 columns]

In [14]:
df.loc[df['total_rooms']%2==0,['total_rooms','total_bedrooms']]

total_rooms  total_bedrooms
0           5612.0          1283.0
1           7650.0          1901.0
2            720.0           174.0
4           1454.0           326.0
7            812.0           168.0
...            ...             ...
16992       1112.0           209.0
16993       2694.0           453.0
16994       1430.0           419.0
16998       2672.0           552.0
16999       1820.0           300.0

[8355 rows x 2 columns]

# ***Iloc passes axis number if rows and columns.***

In [20]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [23]:
# Print 2-3-5-6
print(a[0:2,1:3])

[[2 3]
 [5 6]]


In [24]:
#Syntax :- df.iloc[row_index, col__index]
df.iloc[0:10, 0:5]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0
5    -114.58     33.63                29.0       1387.0           236.0
6    -114.58     33.61                25.0       2907.0           680.0
7    -114.59     34.83                41.0        812.0           168.0
8    -114.59     33.61                34.0       4789.0          1175.0
9    -114.60     34.83                46.0       1497.0           309.0

In [25]:
# Print the even index row up to the 100 for the first 3 cols
df.iloc[[0:100:2, 0:3]%2==0]

longitude  latitude  housing_median_age
0       False     False               False
2       False     False               False
4       False     False                True
6       False     False               False
8       False     False                True
10      False     False                True
12      False     False                True
14      False     False               False
16      False     False                True
18      False     False               False
20      False     False                True
22      False     False                True
24      False     False                True
26      False     False                True
28      False     False                True
30      False     False                True
32      False     False                True
34      False     False               False
36      False     False               False
38      False     False               False
40      False     False               False
42      False     False               False
44      False     False                True
46      False     False                True
48      False     False                True
50      False     False                True
52      False     False                True
54      False     False                True
56      False     False                True
58      False     False                True
60      False     False               False
62      False     False                True
64      False     False               False
66      False     False               False
68      False     False               False
70      False     False                True
72      False     False               False
74      False     False                True
76      False     False               False
78      False     False               False
80      False     False                True
82      False     False                True
84      False     False               False
86      False     False               False
88      False     False               False
90      False     False                True
92      False     False                True
94      False     False               False
96      False     False                True
98      False     False               False

In [28]:
df.loc[df['total_rooms'] % 2 == 0, :]


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
4        -114.57     33.57                20.0       1454.0           326.0   
7        -114.59     34.83                41.0        812.0           168.0   
...          ...       ...                 ...          ...             ...   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
4           624.0       262.0         1.9250             65500.0  
7           375.0       158.0         1.7083             48500.0  
...           ...         ...            ...                 ...  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[8355 rows x 9 columns]

In [ ]:
# Difference between loc and iloc

# df.loc is label-based and supports conditional filtering
# df.iloc is integer position-based and does NOT support conditional filtering

df['col'].loc[start:end:step]

# apply condition
df.loc[df['col'] % 2 == 0]


In [ ]:
# 1st: Column selection (label-based)
df['col']
df[['col1', 'col2', 'col3']]

# 2nd: Label-based row/column selection (supports conditions)
df.loc[start:end:step]

# 3rd: Integer position-based selection
df.iloc[row_index, col_index]


***Handling the missing data***

In [29]:
from numpy import nan as NA

In [34]:
df = pd.DataFrame([[1,2,3],[4,NA,5],[NA, NA, NA]])
print(df)

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN


In [35]:
#Check the null value's
df.isnull()

0      1      2
0  False  False  False
1  False   True  False
2   True   True   True

In [36]:
#how can We Drop the null value
df.dropna()

0    1    2
0  1.0  2.0  3.0

In [37]:
#Delete the rows which have entire null value's
df.dropna(how='all')

0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0

In [39]:
#replace the 2 with null value
df[1]=NA
df

0   1    2
0  1.0 NaN  3.0
1  4.0 NaN  5.0
2  NaN NaN  NaN

In [40]:
#Delete the columns Which having all null value
df.dropna(axis=1, how='all')

0    2
0  1.0  3.0
1  4.0  5.0
2  NaN  NaN